-- AlterTable
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "publishedUrl" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "publishedAt" TIMESTAMP(3);
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "publishPlatform" TEXT;
